### PR TITLE
Adjust page token validation

### PR DESCRIPTION
**Pull request by jchadwick-buf**
We wanted to either pick some arbitrary large value or remove it entirely. Others pointed out that 255 is short enough that it might be a bit too small for base64'd cursor pagination, so I picked 4096 as an arbitrary value.

The justification for this is that _removing_ validation later would be backwards compatible, but adding validation later would be backwards incompatible. So a lenient limit seems like a decent idea.

I think this is the last of the validation issues. I made a couple additional passes to make sure and didn't see anything else that obviously needed attention.

### CODE REVIEW

**Comment by bufdev** [comment]
> The justification for this is that removing it later would be backwards compatible, but adding it later would not be. So a lenient limit seems like a decent idea.

I think it's the opposite, right?

**Comment by jchadwick-buf** [comment]
If you want it removed, I'm happy to go that way, too; nobody really had much of a consensus. But I think it would be a breaking change to add validation: it would reject requests that used to be considered valid. Right? Whereas removing validation shouldn't break any existing clients.

**Review by bufdev — APPROVED** [review]
I was just saying I think you got the wording backwards in the PR description, I think we're on the same page but you have the inverse in the description :-)

**Comment by jchadwick-buf** [comment]
Ah, alright. I tried to make the PR description a bit clearer just for posterity's sake.

**Pull request merged**
